lists=[1,3,6,8]
# lists.append(3)
# print(lists)
# lists.remove(3)
# print(lists)
# lists.sort()
# print(lists)
# lists.insert(1,9) 
# print(lists)
# lists.pop(3)
# print(lists)
# lists.pop()
# print(lists)
# lists.index(1)
# print(lists)
# lists.count(3)
# print(lists)
# lists.sort()
# print(lists)
# lists.reverse()
# print(lists)

